### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by maacl** [sgrove/gamma-playground#10]
I am seeing some warnings when executing (run) and (browser-repl):

`WARNING: mask already refers to: /mask being replaced by: gamma-driver.common.draw/mask at line 7 file:/Users/mac/.m2/repository/kovasb/gamma-driver/0.1.0-SNAPSHOT/gamma-driver-0.1.0-SNAPSHOT.jar!/gamma_driver/common/draw.cljs`

**Comment by sgrove** [comment]
Thanks for that! Tracking that upstream at `gamma-driver` here https://github.com/kovasb/gamma-driver/issues/4
