### ISSUE TITLE
how to show lessons 2-n?

### ISSUE THREAD

**Issue by postspectacular** [sgrove/gamma-playground#9]
Hi Sean, thanks for the effort, but how do you switch/navigate to show not just the first lesson? :)

**Comment by sgrove** [comment]
Goooood question! Just change https://github.com/sgrove/gamma-playground/blob/master/src/cljs/gampg/core.cljs#L28 these lines from lg01/... to e.g. lg02/...

Also, I plan to have a side-bar for going through the examples (see TODO here https://github.com/sgrove/gamma-playground/blob/master/src/cljs/gampg/core.cljs#L24), and I'm pondering following your literate coding style, to have the menu, tutorial, and live examples running alongside each other.

**Comment by sgrove** [comment]
@postspectacular Let me know if that worked for you so I can close this issue.

**Comment by postspectacular** [comment]
@sgrove it worked, indeed! Great stuff! :)
